/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_antoniomayk_jwhisper_jni_WhisperCpp */

#ifndef _Included_io_github_antoniomayk_jwhisper_jni_WhisperCpp
#define _Included_io_github_antoniomayk_jwhisper_jni_WhisperCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperInitFromFileWithParams
 * Signature: (Ljava/lang/String;Lio/github/antoniomayk/jwhisper/jni/WhisperContextParams;)Lio/github/antoniomayk/jwhisper/jni/WhisperContext;
 */
JNIEXPORT jobject JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperInitFromFileWithParams
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFree
 * Signature: (Lio/github/antoniomayk/jwhisper/jni/WhisperContext;)V
 */
JNIEXPORT void JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFree
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFreeParams
 * Signature: (Lio/github/antoniomayk/jwhisper/jni/WhisperFullParams;)V
 */
JNIEXPORT void JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFreeParams
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFreeContextParams
 * Signature: (Lio/github/antoniomayk/jwhisper/jni/WhisperContextParams;)V
 */
JNIEXPORT void JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFreeContextParams
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperContextDefaultParamsByRef
 * Signature: ()Lio/github/antoniomayk/jwhisper/jni/WhisperContextParams;
 */
JNIEXPORT jobject JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperContextDefaultParamsByRef
  (JNIEnv *, jclass);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFullDefaultParamsByRef
 * Signature: (I)Lio/github/antoniomayk/jwhisper/jni/WhisperFullParams;
 */
JNIEXPORT jobject JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFullDefaultParamsByRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFull
 * Signature: (Lio/github/antoniomayk/jwhisper/jni/WhisperContext;Lio/github/antoniomayk/jwhisper/jni/WhisperFullParams;[FI)V
 */
JNIEXPORT void JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFull
  (JNIEnv *, jclass, jobject, jobject, jfloatArray, jint);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFullNumberOfSegments
 * Signature: (Lio/github/antoniomayk/jwhisper/jni/WhisperContext;)I
 */
JNIEXPORT jint JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFullNumberOfSegments
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFullGetSegmentText
 * Signature: (Lio/github/antoniomayk/jwhisper/jni/WhisperContext;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFullGetSegmentText
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFullGetSegmentT0
 * Signature: (Lio/github/antoniomayk/jwhisper/jni/WhisperContext;I)J
 */
JNIEXPORT jlong JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFullGetSegmentT0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFullGetSegmentT1
 * Signature: (Lio/github/antoniomayk/jwhisper/jni/WhisperContext;I)J
 */
JNIEXPORT jlong JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFullGetSegmentT1
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
