/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_antoniomayk_jwhisper_jni_WhisperCpp */

#ifndef _Included_io_github_antoniomayk_jwhisper_jni_WhisperCpp
#define _Included_io_github_antoniomayk_jwhisper_jni_WhisperCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperInitFromFileWithParams
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperInitFromFileWithParams
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFreeParams
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFreeParams
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFreeContextParams
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFreeContextParams
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperContextDefaultParamsByRef
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperContextDefaultParamsByRef
  (JNIEnv *, jclass);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFullDefaultParamsByRef
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFullDefaultParamsByRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFull
 * Signature: (JJ[FI)I
 */
JNIEXPORT jint JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFull
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jint);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFullNumberOfSegments
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFullNumberOfSegments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_antoniomayk_jwhisper_jni_WhisperCpp
 * Method:    whisperFullGetSegmentText
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_antoniomayk_jwhisper_jni_WhisperCpp_whisperFullGetSegmentText
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
